### ISSUE TITLE
main page is crashing

### ISSUE THREAD

**Issue by piraces** [vinliao/nashboard#10]
Hello there!

I open this issue to let you know that the [nashboard.space](https://nashboard.space/) is crashing right now...
It appears to be something related with a Netlify function, since accessing [https://nashboard.space/wlvs.space](https://nashboard.space/wlvs.space) returns this kind of error:
![Crash screenshot](https://i.imgur.com/eEmbHfU.png)

`Netlify internal ID: 01GP3DADW8XGY22WE53NR910YQ`

**Comment by vinliao** [comment]
Fixed. Thanks for raising the issue.

![image](https://user-images.githubusercontent.com/34117807/211012423-902ef60f-411e-417e-aeef-ce744349a1f9.png)
